---

- hosts: all
  become: true
  tasks:

  - name: Update repo index, install Apache and PHP support for it
    apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Update repo index, install Apache and PHP support for it
    dnf:
      name:
      - httpd
      - php
      update_cache: yes
    when: ansible_distribution == "CentOS"
