---

- hosts: all
  become: true
  tasks:

  - name: Remove Apache and PHP packages
    apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
    when: ansible_distribution in ["Debian", "Ubuntu"]
