---

- hosts: all
  become: true
  tasks:

  - name: Remove Apache package
    apt:
      name: apache2
      state: absent

  - name: Remove PHP for Apache
    apt:
      name: libapache2-mod-php
      state: absent
