---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
  - name: create new user
    tags: always
    user:
      name: newuser111
      groups: root

  - name: add sudoers file for newuser111
    tags: always
    copy:
      src: sudoer_newuser111
      dest: /etc/sudoers.d/newuser111
      owner: root
      group: root
      mode: 0440

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: database_servers
  become: true
  roles:
    - database_servers
